---

- name: Ensure VS Code Repository key exists
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Ensure APT repository file exists
  apt_repository:
    repo: "deb https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode

- name: Ensure VS Code is installed
  apt:
    name: code
    state: present
    update_cache: true
